import csv
import subprocess
import os

repo_root = "/Users/neomunuke/CS472/rootbeer"  # path to your cloned rootbeer repo
csv_file = "data/file_rootbeer.csv" # CSV generated by CollectFiles.py
output_file = "file_touches.csv"  # output CSV for authors/dates

files = []
with open(csv_file, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        filename = row["Filename"]
        full_path = os.path.join(repo_root, filename)
        if os.path.exists(full_path):
            files.append(filename)
        else:
            print(f"Skipping {filename}, not found locally.")

print(f"Found {len(files)} source files locally.")

def get_file_history(file):
    # Use git -C to specify the repo root
    cmd = ["git", "-C", repo_root, "log", "--follow", "--format=%an|%ad", "--", file]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Git command failed for {file}")
        return []
    return result.stdout.strip().split("\n")

os.makedirs("data", exist_ok=True)
with open(output_file, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["file", "author", "date"])

    for file in files:
        history = get_file_history(file)
        if not history:
            continue
        for line in history:
            if "|" in line:
                author, date = line.split("|", 1)
                writer.writerow([file, author.strip(), date.strip()])

print(f"Author history written to {output_file}")
